server:
  port: 8989
spring:
  application:
    name: springboot-boot-test
  datasource:
    url: jdbc:mysql://${mysqladdr}:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ${name}
    password: ${pass}